// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: common_response.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APICommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APICommonResponse) Reset() {
	*x = APICommonResponse{}
	mi := &file_common_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APICommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APICommonResponse) ProtoMessage() {}

func (x *APICommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APICommonResponse.ProtoReflect.Descriptor instead.
func (*APICommonResponse) Descriptor() ([]byte, []int) {
	return file_common_response_proto_rawDescGZIP(), []int{0}
}

func (x *APICommonResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *APICommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *APICommonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *APICommonResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_common_response_proto protoreflect.FileDescriptor

const file_common_response_proto_rawDesc = "" +
	"\n" +
	"\x15common_response.proto\x12\x04user\"q\n" +
	"\x11APICommonResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x04 \x01(\x05R\x04codeB\x03Z\x01.b\x06proto3"

var (
	file_common_response_proto_rawDescOnce sync.Once
	file_common_response_proto_rawDescData []byte
)

func file_common_response_proto_rawDescGZIP() []byte {
	file_common_response_proto_rawDescOnce.Do(func() {
		file_common_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_response_proto_rawDesc), len(file_common_response_proto_rawDesc)))
	})
	return file_common_response_proto_rawDescData
}

var file_common_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_response_proto_goTypes = []any{
	(*APICommonResponse)(nil), // 0: user.APICommonResponse
}
var file_common_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_response_proto_init() }
func file_common_response_proto_init() {
	if File_common_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_response_proto_rawDesc), len(file_common_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_response_proto_goTypes,
		DependencyIndexes: file_common_response_proto_depIdxs,
		MessageInfos:      file_common_response_proto_msgTypes,
	}.Build()
	File_common_response_proto = out.File
	file_common_response_proto_goTypes = nil
	file_common_response_proto_depIdxs = nil
}
