// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: user_service.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_user_service_proto protoreflect.FileDescriptor

const file_user_service_proto_rawDesc = "" +
	"\n" +
	"\x12user_service.proto\x12\x04user\x1a\vlogin.proto\x1a\x15common_response.proto\x1a\fsignup.proto2m\n" +
	"\x04user\x125\n" +
	"\x06Signup\x12\x12.user.NewUserInput\x1a\x17.user.APICommonResponse\x12.\n" +
	"\x05Login\x12\x10.user.LoginInput\x1a\x13.user.LoginResponseB\x03Z\x01.b\x06proto3"

var file_user_service_proto_goTypes = []any{
	(*NewUserInput)(nil),      // 0: user.NewUserInput
	(*LoginInput)(nil),        // 1: user.LoginInput
	(*APICommonResponse)(nil), // 2: user.APICommonResponse
	(*LoginResponse)(nil),     // 3: user.LoginResponse
}
var file_user_service_proto_depIdxs = []int32{
	0, // 0: user.user.Signup:input_type -> user.NewUserInput
	1, // 1: user.user.Login:input_type -> user.LoginInput
	2, // 2: user.user.Signup:output_type -> user.APICommonResponse
	3, // 3: user.user.Login:output_type -> user.LoginResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_service_proto_init() }
func file_user_service_proto_init() {
	if File_user_service_proto != nil {
		return
	}
	file_login_proto_init()
	file_common_response_proto_init()
	file_signup_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_proto_rawDesc), len(file_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_proto_goTypes,
		DependencyIndexes: file_user_service_proto_depIdxs,
	}.Build()
	File_user_service_proto = out.File
	file_user_service_proto_goTypes = nil
	file_user_service_proto_depIdxs = nil
}
