// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type APICommonResponse struct {
	Error   string `json:"error"`
	Message string `json:"message"`
	Success bool   `json:"success"`
	Code    int32  `json:"code"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Common       *APICommonResponse `json:"common"`
	BearerToken  string             `json:"bearerToken"`
	RefreshToken string             `json:"refreshToken"`
}

type Mutation struct {
}

type NewUserInput struct {
	PreferredName string `json:"preferredName"`
	Email         string `json:"email"`
	Password      string `json:"password"`
}

type Query struct {
}
